In [3]:
! pip3 install yfinance

Collecting yfinance
  Downloading yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: requests>=2.20 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from yfinance) (2.26.0)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.10.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from yfinance) (1.21.2)
Requirement already satisfied: pandas>=0.24 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from yfinance) (1.3.3)
Requirement already satisfied: lxml>=4.5.1 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from yfinance) (4.6.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from pandas>=0.24->yfinance) (2021.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from requests>=2.20->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from requests>=2.20->yfinance) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from requests>=2.20->yfinance) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from requests>=2.20->yfinance) (2021.10.8)
Requirement already satisfied: six>=1.5 in /Volumes/iPort/opt/miniconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.16.0)
Using legacy 'setup.py install' for multitasking, since package 'wheel' is not installed.
Installing collected packages: multitasking, yfinance
    Running setup.py install for multitasking ... done
Successfully installed multitasking-0.0.10 yfinance-0.1.67

In [4]:
# Import package
import yfinance as yf

In [39]:
get_tick = ['AMC', 'GME', 'TSLA', 'MSFT', 'AAPL', 'NKLA', 'GOOGL','RIVN', 'FB']

# Get the data
for ticker in get_tick:
    data = yf.download(tickers=ticker, period="1mo", interval="15m")
    data.to_csv(ticker+'.csv')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [38]:
data

                            Adj Close                                     \
                                 AAPL        AMC          FB         GME
Datetime
2021-11-03 09:30:00-04:00  150.710007  42.424999  326.114990  228.264999
2021-11-03 09:45:00-04:00  150.720001  42.478699  328.640015  238.541199
2021-11-03 10:00:00-04:00  150.550003  43.138500  327.420013  238.489899
2021-11-03 10:15:00-04:00  150.615005  42.037998  328.260010  233.600006
2021-11-03 10:30:00-04:00  150.370804  41.589901  327.470001  226.134995
...                               ...        ...         ...         ...
2021-12-02 15:00:00-05:00  163.559998  29.971001  310.049988  181.649994
2021-12-02 15:15:00-05:00  163.460007  30.348000  309.779999  180.929993
2021-12-02 15:30:00-05:00  163.930099  30.320000  310.920013  181.080002
2021-12-02 15:45:00-05:00  163.789993  30.273500  310.380005  181.710007
2021-12-02 16:00:00-05:00  163.759995  30.280001  310.390015  181.559998

                                                                         \
                                 GOOGL        MSFT     NKLA        RIVN
Datetime
2021-11-03 09:30:00-04:00  2903.020020  332.720001  12.5900         NaN
2021-11-03 09:45:00-04:00  2911.324951  332.850006  12.6300         NaN
2021-11-03 10:00:00-04:00  2904.850098  331.739990  12.6300         NaN
2021-11-03 10:15:00-04:00  2902.250000  330.859985  12.6900         NaN
2021-11-03 10:30:00-04:00  2900.000000  331.070007  12.7400         NaN
...                                ...         ...      ...         ...
2021-12-02 15:00:00-05:00  2863.540039  330.040009   9.9150  111.800102
2021-12-02 15:15:00-05:00  2860.570068  329.959991   9.8915  111.184998
2021-12-02 15:30:00-05:00  2872.870117  330.799988   9.9450  111.610001
2021-12-02 15:45:00-05:00  2858.320068  329.489990   9.8900  110.739998
2021-12-02 16:00:00-05:00  2859.320068  329.489990   9.8800  110.769997

                                             Close  ...         Open   Volume  \
                                  TSLA        AAPL  ...         TSLA     AAPL
Datetime                                            ...
2021-11-03 09:30:00-04:00  1187.569946  150.710007  ...  1183.609985  5682459
2021-11-03 09:45:00-04:00  1178.400024  150.720001  ...  1188.000000  2569474
2021-11-03 10:00:00-04:00  1177.807251  150.550003  ...  1178.569946  1782482
2021-11-03 10:15:00-04:00  1183.329956  150.615005  ...  1177.750000  1499438
2021-11-03 10:30:00-04:00  1177.329956  150.370804  ...  1182.699951  1318991
...                                ...         ...  ...          ...      ...
2021-12-02 15:00:00-05:00  1081.010010  163.559998  ...  1082.060059  2975943
2021-12-02 15:15:00-05:00  1078.400024  163.460007  ...  1081.738525  2178467
2021-12-02 15:30:00-05:00  1083.930054  163.930099  ...  1078.479980  3489243
2021-12-02 15:45:00-05:00  1084.530029  163.789993  ...  1084.369995  7166851
2021-12-02 16:00:00-05:00  1084.599976  163.759995  ...  1084.599976        0

                                                                        \
                                AMC       FB      GME   GOOGL     MSFT
Datetime
2021-11-03 09:30:00-04:00  12498302  2045618  1196859  100636  1927080
2021-11-03 09:45:00-04:00   6512424  1263413  1362208   48526   813327
2021-11-03 10:00:00-04:00  12518218   810800  2641512   58670   829974
2021-11-03 10:15:00-04:00   6381643   681725   892256   41821   794429
2021-11-03 10:30:00-04:00   4939501   714761   803640   25095   602697
...                             ...      ...      ...     ...      ...
2021-12-02 15:00:00-05:00    738870   603593    34166   26280   934577
2021-12-02 15:15:00-05:00   1163895   592507    36205   18239   793044
2021-12-02 15:30:00-05:00    998591   834823    27366   40921  1030702
2021-12-02 15:45:00-05:00   1690031  1581721   135142  184281  3064579
2021-12-02 16:00:00-05:00         0        0        0       0        0


                              NKLA      RIVN     TSLA
Datetime
2021-11-03 09:30:00-04:00  1289525       NaN  3495523
2021-11-03 09:45:00-04:00   632292       NaN  1985694
2021-11-03 10:00:00-04:00   341034       NaN  1410495
2021-11-03 10:15:00-04:00   475322       NaN  1150173
2021-11-03 10:30:00-04:00   377809       NaN   730885
...                            ...       ...      ...
2021-12-02 15:00:00-05:00   314701  161747.0   825603
2021-12-02 15:15:00-05:00   161252  149738.0   556205
2021-12-02 15:30:00-05:00   308686  152610.0   609122
2021-12-02 15:45:00-05:00   744337  532725.0   983844
2021-12-02 16:00:00-05:00        0       0.0        0

[536 rows x 54 columns]